alanber/webapp/views/user.py
# coding:utf8

"""
Copyright 2016 Smallpay Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import json
import base64
from flask import Blueprint, render_template, request

from alanber.webapp.views import USER_WXCORP_MAP, UserCache
from alanber.weixin.corp.api import CorpApi
from alanber.weixin.corp.oauth import authorize


bp = Blueprint('user', __name__)


@bp.route('/info')
@authorize
def info():
    userinfo = json.loads(base64.b64decode(request.cookies.get('userinfo')))
    userid = userinfo.get('userid')
    is_follow = userid and True or False

    user = {}
    if is_follow:
        user = CorpApi().get_user(userid)
        if user.has_key('extattr'):
            extattrs = user['extattr']['attrs']
            for attr in extattrs:
                if attr['name'] == USER_WXCORP_MAP.get('cn_birthday'):
                    user['cn_birthday'] = attr['value']
            for attr in extattrs:
                if attr['name'] == USER_WXCORP_MAP.get('gr_birthday'):
                    user['gr_birthday'] = attr['value']
        UserCache.put(user)
    return render_template('user/info.html', user=user, is_follow=is_follow)


@bp.route('/update/<userid>', methods=['GET', 'POST'])
@authorize
def update(userid):
    user = UserCache.get(userid)

    if request.method == 'GET':
        return render_template('user/update.html', user=user)
    elif request.method == 'POST':
        phone = request.form.get('phone')
        cn_birthday = request.form.get('cn_birthday')
        gr_birthday = request.form.get('gr_birthday')
        kwargs = dict()

        if phone:
            kwargs['mobile'] = phone
        else:
            kwargs['mobile'] = user.get('mobile')

        if cn_birthday or gr_birthday:
            extattrs = []
            if cn_birthday:
                extattrs.append(dict(name=USER_WXCORP_MAP.get('cn_birthday'), value=cn_birthday))
            if gr_birthday:
                extattrs.append(dict(name=USER_WXCORP_MAP.get('gr_birthday'), value=gr_birthday))
            kwargs['extattrs'] = extattrs
        CorpApi().update_user(userid, **kwargs)
        return render_template('user/ok.html')

alanber/webapp/templates/user/info.html
{% extends "base.html" %}
{% block body %}
<div class="container" id="container">
    <div class="hd">
        <h3 class="page_title">欢迎加入彭家湾亲友会</h3>
    </div>
    <div class="bd">
        {% if is_follow %}
        <div class="weui_cells">
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>姓名</p>
                </div>
                <div class="weui_cell_ft">
                    {{ user.name }}
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>性别</p>
                </div>
                <div class="weui_cell_ft">
                    {{ user.gender|gender_translate }}
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>手机号</p>
                </div>
                <div class="weui_cell_ft">
                    {{ user.mobile }}
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>农历生日</p>
                </div>
                <div class="weui_cell_ft">
                    {{ user.cn_birthday }}
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_bd weui_cell_primary">
                    <p>公历生日</p>
                </div>
                <div class="weui_cell_ft">
                    {{ user.gr_birthday }}
                </div>
            </div>
        </div>
        <a href="{{ url_for('user.update', userid=user.userid) }}" class="weui_btn weui_btn_primary">我要更新信息</a>
        {% else %}
        <div class="weui_msg">
            <div class="weui_text_area">
                <h2 class="weui_msg_title">亲爱的微信用户 {{ user.nickname }}</h2>
                <p class="weui_msg_desc">您还没有关注彭家湾亲友会,请长按下面的二维码进行关注</p>
            </div>
            <div class="weui_opr_area">
                <img src="{{ url_for('static', filename='img/qrcode_for_pjwqyh_258.jpg') }}" />
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block javascript %}
{% endblock %}

alanber/webapp/templates/user/ok.html
{% extends "base.html" %}
{% block body %}
<div class="weui_msg">
    <div class="weui_icon_area"><i class="weui_icon_success weui_icon_msg"></i></div>
    <div class="weui_text_area">
        <h2 class="weui_msg_title">个人用户信息修改成功</h2>
    </div>
    <div class="weui_opr_area">
        <p class="weui_btn_area">
            <a href="{{ url_for('user.info') }}" class="weui_btn weui_btn_primary">确定</a>
        </p>
    </div>
</div>
{% endblock %}

alanber/webapp/templates/user/update.html
{% extends "base.html" %}
{% block body %}
<div class="container" id="container">
    <div class="hd">
        <h3 class="page_title">请更新您的信息</h3>
    </div>
    <div class="bd">
        <form class="weui_cells weui_cells_form" id="userForm" method="post">
            <div class="weui_cell">
                <div class="weui_cell_hd"><label class="weui_label">手机号码</label></div>
                <div class="weui_cell_bd weui_cell_primary">
                    <input class="weui_input" type="tel" name="phone" placeholder="请输入手机号码" value="{{ user.mobile }}">
                </div>
            </div>
            <div class="weui_cells_title">公历生日和农历生日二选一即可</div>
            <div class="weui_cell">
                <div class="weui_cell_hd weui_cell_primary">农历生日</div>
                <div class="weui_cell_bd weui_cell_primary">
                    <input class="weui_input" type="text" id="cnDate" name="cn_birthday" value="{{ user.cn_birthday }}">
                </div>
            </div>
            <div class="weui_cell">
                <div class="weui_cell_hd"><label class="weui_label">公历生日</label></div>
                <div class="weui_cell_bd weui_cell_primary">
                    <input class="weui_input" type="text" id="grDate" name="gr_birthday" value="{{ user.gr_birthday }}">
                </div>
            </div>
            <div class="weui_cell">
                <button class="weui_btn weui_btn_primary" onclick="submitUser()">确认提交</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
    $("#cnDate").calendar({
        value: ["1980-01-01"]
    });
    $("#grDate").calendar({
        value: ["1980-01-01"]
    });

    function submitUser() {
        $("#userForm").submit();
    }
</script>
{% endblock %}